# Generated by Django 6.0.5 on 2026-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Клиника/адрес'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, max_length=200, verbose_name='Учёная степень/категория'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization_list',
            field=models.TextField(blank=True, help_text='Специализация (каждый пункт с новой строки)', verbose_name='Специализация (подробно)'),
        ),
    ]
